FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Père Castor

Polls is a simple API allowing consumers to view polls and vote in them.

## Authentication [/auth/]

### Authenticate a user [POST]

+ Request (application/json)

        {
            "login": "foo",
            "password": "bar"
        }

+ Response 200 (application/json)

        {
            id: "15ds1xc",
            token: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJfaWQiOiI1NDY1MDViMDFmYTAzYmUwMTUxMDYwOWIiLCJuYW1lIjoiTmljayBDZXJtaW5hcmEiLCJwYXNzd29yZCI6InBhc3N3b3JkIiwiYWRtaW4iOnRydWUsIl9fdiI6MH0.ah-NFQ1967WVeN6lYNAahT7hZtshG6kw6AW3ncuJOYw"
        }

+ Response 401 (application/json)


+ Response 403 (application/json)

## User Collection [/api/users]

### Create a user [POST /api/users/]

+ Request (application/json)

        {
            "login": "foo",
            "password": "bar",
            "email": "foo@bar.fr",
            "mainStory": "foobar"
        }

+ Response 200 (application/json)

        {
            id: "15ds1xc",
            token: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJfaWQiOiI1NDY1MDViMDFmYTAzYmUwMTUxMDYwOWIiLCJuYW1lIjoiTmljayBDZXJtaW5hcmEiLCJwYXNzd29yZCI6InBhc3N3b3JkIiwiYWRtaW4iOnRydWUsIl9fdiI6MH0.ah-NFQ1967WVeN6lYNAahT7hZtshG6kw6AW3ncuJOYw"
        }

+ Response 401 (application/json)


+ Response 403 (application/json)